Style/Documentation:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/BlockLength:
  Max: 30
Layout/EndOfLine:
  Enabled: false
