approvedGitRepositories:
  - "ssh://git@github.com/user-komeda/*"

checksumBehavior: throw

enableScripts: false

enableStrictSsl: true

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages: [ ]

yarnPath: .yarn/releases/yarn-4.16.0.cjs
