services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    profiles:
      - frontend
    restart: always
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    profiles:
      - backend
    restart: always
    ports:
      - "4567:4567"
  db:
    container_name: db
    image: postgres:18@sha256:55586516b2fd477faa8f0f05ec0a72b196fb7e2bce8df3adfb9c6a0ed607214f
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: redis:8.6@sha256:1c054d54ecd1597bba52f4304bca5afbc5565ebe614c5b3d7dc5b7f8a0cd768d
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --protected-mode yes
      --requirepass password
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
  redis-data:
