services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      ssh:
        - default
    profiles:
      - frontend
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      ssh:
        - default
    profiles:
      - backend
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "4567:4567"
  db:
    container_name: db
    image: postgres:18@sha256:1a5b3e745bbd82d6deb146505e504da3c2f248cac15e431951b148fbe4f8613a
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: redis:8.8@sha256:027002f3d4161eb427643e0cc71023b582fb461c6199e699f46db843f0b39fb1
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --protected-mode yes
      --requirepass password
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:
  redis-data:
