
module ROM
  class Relation
    type adapter = :sql | :http | :yaml | untyped

    def self.[]: (adapter) -> singleton(Relation)

    def where: (**untyped) -> Relation
    def order: (*Symbol | String) -> Relation
    def limit: (Integer) -> Relation
    def offset: (Integer) -> Relation
    def select: (*Symbol | String) -> Relation
    def by_pk: (untyped) -> Relation
    def by_email: (untyped) -> Relation
    def one: () -> untyped
    def one!: () -> untyped
    def first: () -> untyped
    def to_a: () -> Array[untyped]
    def map_to: (untyped) -> Relation
    def combine: (*Symbol) -> Relation
    def wrap: (*Symbol) -> Relation
    def group: (*Symbol) -> Relation
    def each: () { (untyped) -> void } -> void
    # Returns a command object (e.g., :create) which responds to `call`
    def command: (Symbol) -> untyped

    def self.schema: (Symbol, ?infer: bool) ?{ () -> void } -> void

    # ROM associations DSL used inside relation schema blocks
    def self.associations: () { () -> void } -> void
    def self.belongs_to: (Symbol) -> void
    def self.has_one: (Symbol) -> void
  end
end
