module ROM
  class Repository[T]
    def self.[]: (Symbol) -> untyped
    def self.commands: (*Symbol | Hash[Symbol, Symbol]) -> void

    def users: () -> ::Infrastructure::Relations::Users
    def auth_users: () -> ::Infrastructure::Relations::AuthUsers
    def work_spaces: () -> ::Infrastructure::Relations::WorkSpace
    def member_ships: () -> ::Infrastructure::Relations::MemberShips

    def create: (untyped) -> untyped
    def update: (untyped, untyped) -> untyped
    def delete: (untyped) -> untyped

    def self.include: (untyped) -> void
  end
end
