# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma', '~> 8.0'
gem 'rackup', '~> 2.2'
gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib', '~> 4.1'

gem 'dry-auto_inject', '~> 1.1'
gem 'dry-system', '~> 1.2'
gem 'dry-validation'
gem 'zeitwerk', '~> 2.7'

gem 'rom', '~> 5.4'
gem 'rom-repository', '~> 5.4'
gem 'rom-sql', '~> 3.7'

gem 'pg', require: false
gem 'rack-protection'
gem 'rake'
gem 'rbs-inline', '0.14.0'
gem 'ridgepole'

gem 'dotenv', '~> 3.1'

gem 'bcrypt'
gem 'jwt'
gem 'rack-unreloader'
gem 'redis'

group :development, :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop', '< 1.87.1'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubycritic', '~> 5.0'
  gem 'steep', '~> 2.0'
end

group :test do
  gem 'openapi_first',
      git: 'git@github.com:user-komeda/openapi_first_for_me.git',
      branch: 'main'
  gem 'simplecov', require: false
end

gem 'bundler-audit', '~> 0.9.3', groups: %i[development test], require: false
