# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'sinatra', '~> 4.1'

gem 'puma', '~> 7.0'
gem 'rackup', '~> 2.2'

gem 'sinatra-contrib', '~> 4.1'

gem 'dry-auto_inject', '~> 1.1'
gem 'dry-system', '~> 1.2'
gem 'dry-validation'
gem 'zeitwerk', '~> 2.7'

gem 'rom', '~> 5.4'
gem 'rom-repository', '~> 5.4'
gem 'rom-sql', '~> 3.7'

gem 'rubocop', '< 1.82.1'
gem 'rubocop-performance', require: false
gem 'rubocop-rake', require: false
gem 'rubocop-rspec', require: false

gem 'rubycritic', '~> 4.9'

gem 'steep', '~> 1.10'

gem 'infisical-sdk'
gem 'pg', require: false
gem 'rack-protection'
gem 'rake'
gem 'rbs-inline', '0.12.0'
gem 'ridgepole'

gem 'dotenv', '~> 3.1'

gem 'rack-test'
gem 'rspec'
gem 'simplecov', require: false, group: :test

gem 'bcrypt'
gem 'rack-unreloader'
gem 'redis'
