# frozen_string_literal: true

# Rakefile
require 'rake'
require_relative 'config/auto_load'
require 'dotenv/load'

# lib/tasks 以下の rake タスクを全て読み込む
Dir.glob('tasks/**/*.rake').each { |file| load file }
