# frozen_string_literal: true

# Rakefile
require 'rake'
require_relative 'config/auto_load'
require 'dotenv/load'

if ENV.fetch('APP_RUNTIME_ONLY', 'false') == 'true'
  load 'tasks/app.rake'
else
  Dir.glob('tasks/**/*.rake').each { |file| load file }
end
