# frozen_string_literal: true

D = Steep::Diagnostic
target :lib do
  signature 'sig'
  library 'securerandom' # この行を追加
  ignore_signature 'sig/test'
  check 'lib' # Directory name
  configure_code_diagnostics(D::Ruby.default)
end

# target :test do
#   unreferenced!                     # Skip type checking the `lib` code when types in `test` target is changed
#   signature "sig_tmp/test"              # Put RBS files for tests under `sig_tmp/test`
#   check "test"                      # Type check Ruby scripts under `test`
#
#   configure_code_diagnostics(D::Ruby.lenient)      # Weak type checking for test code
#
#   # library "pathname"              # Standard libraries
# end
