/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * ユーザー一覧の取得
     * @description 登録済みユーザーの一覧を返します。
     */
    get: operations['listUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * ユーザー詳細の取得
     * @description 指定 ID のユーザーを返します。
     */
    get: operations['getUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** ユーザー情報の更新 */
    patch: operations['updateUser']
    trace?: never
  }
  '/signup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * サインアップ（ユーザー登録）
     * @description 新規ユーザーを登録します。POST + JSON で受け付けます。
     */
    post: operations['signup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/signin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * サインイン（ログイン）
     * @description 既存ユーザーのサインインを行います。POST + JSON で受け付けます。
     */
    post: operations['signin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/work_spaces': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * ワークスペース一覧の取得
     * @description ログインユーザーが所属する（または閲覧可能な）ワークスペースの一覧を返します。
     */
    get: operations['listWorkSpaces']
    put?: never
    /**
     * ワークスペースの作成
     * @description 新しいワークスペースを作成します。
     */
    post: operations['createWorkSpace']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/work_spaces/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** ワークスペース詳細の取得 */
    get: operations['getWorkSpace']
    put?: never
    post?: never
    /** ワークスペースの削除 */
    delete: operations['deleteWorkSpace']
    options?: never
    head?: never
    /** ワークスペースの更新 */
    patch: operations['updateWorkSpace']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description ユーザー情報 */
    User: {
      /**
       * Format: uuid
       * @example 4b0a3b44-2b8f-4a7c-9f08-6b7e1b2c3d4e
       */
      id: string
      /** @example Taro */
      first_name: string
      /** @example Yamada */
      last_name: string
      /**
       * Format: email
       * @example taro.yamada@example.com
       */
      email: string
    }
    /** @description ユーザー作成リクエストボディ */
    CreateUserRequest: {
      first_name: string
      last_name: string
      /** Format: email */
      email: string
    }
    /** @description ユーザー更新リクエストボディ（変更する項目のみ送信） */
    UpdateUserRequest: {
      first_name?: string
      last_name?: string
      /** Format: email */
      email?: string
    }
    ListUsersResponse: components['schemas']['User'][]
    SigninRequest: {
      /**
       * Format: email
       * @description メールアドレス
       */
      email: string
      /** @description パスワード（平文） */
      password: string
    }
    SigninResponse: {
      /** Format: uuid */
      user_id: string
    }
    SignupRequest: {
      /** @description 名 */
      first_name: string
      /** @description 姓 */
      last_name: string
      /**
       * Format: email
       * @description メールアドレス
       */
      email: string
      /** @description パスワード（平文） */
      password: string
    }
    SignupResponse: {
      /** Format: uuid */
      user_id: string
    }
    /** @description ワークスペース情報 */
    WorkSpace: {
      /**
       * Format: uuid
       * @example 4b0a3b44-2b8f-4a7c-9f08-6b7e1b2c3d4e
       */
      id: string
      /** @example 開発チーム */
      name: string
      /** @example dev-team */
      slug: string
    }
    /** @description ステータス付きワークスペース情報 */
    WorkSpaceWithStatus: {
      /**
       * Format: uuid
       * @example 4b0a3b44-2b8f-4a7c-9f08-6b7e1b2c3d4e
       */
      id: string
      /** @example 開発チーム */
      name: string
      /** @example dev-team */
      slug: string
      /** @example active */
      status: string
    }
    /** @description メンバーシップ情報を含むワークスペース作成レスポンス */
    WorkSpaceWithMemberShips: {
      /**
       * Format: uuid
       * @example 4b0a3b44-2b8f-4a7c-9f08-6b7e1b2c3d4e
       */
      id: string
      work_spaces: components['schemas']['WorkSpace']
      member_ships: components['schemas']['MemberShips']
    }
    /** @description メンバーシップ情報 */
    MemberShips: {
      /**
       * Format: uuid
       * @example 5c1b4c55-3c9g-5b8d-0g19-7c8f2c3d4e5f
       */
      id: string
      /**
       * Format: uuid
       * @example 04e8496c-6b8c-4f4f-9746-2d96a10f13ec
       */
      user_id: string
      /**
       * Format: uuid
       * @example 4b0a3b44-2b8f-4a7c-9f08-6b7e1b2c3d4e
       */
      work_space_id: string
      /** @example owner */
      role: string
      /** @example active */
      status: string
    }
    /** @description ワークスペース作成リクエスト */
    CreateWorkSpaceRequest: {
      /** @example 開発チーム */
      name: string
      /** @example dev-team */
      slug: string
    }
    /** @description ワークスペース更新リクエスト */
    UpdateWorkSpaceRequest: {
      /** @example 開発チーム(更新) */
      name?: string
      /** @example dev-team-updated */
      slug?: string
    }
    ListWorkSpacesResponse: {
      data: components['schemas']['WorkSpaceWithStatus'][]
      meta: components['schemas']['PaginationMeta']
    }
    PaginationMeta: {
      /**
       * @description 現在のページ番号
       * @example 1
       */
      page: number
      /**
       * @description 総ページ数
       * @example 5
       */
      total_pages: number
      /**
       * @description 総データ件数
       * @example 100
       */
      total_count: number
      /**
       * @description 1ページあたりの件数
       * @example 20
       */
      per_page: number
      /**
       * @description 現在適用されている検索クエリ
       * @example test
       */
      search_query?: string
    }
    /** @description エラー情報 */
    Error: {
      /**
       * @description エラー種別コード
       * @example BAD_REQUEST
       */
      error_code: string
      /**
       * @description エラーメッセージ
       * @example invalid request body
       */
      message: string
      /** @description フィールド単位のエラー情報 */
      field_errors?: {
        key: string
        message: string
      }[]
    }
  }
  responses: never
  parameters: {
    /** @description ユーザーID(UUID) */
    UserId: string
    /** @description ワークスペースID(UUID) */
    WorkSpaceId: string
    /** @description ページ番号 */
    Page: number
    /** @description 1ページあたりの件数 */
    PerPage: number
    /** @description 検索クエリ（名前などでフィルタリング） */
    SearchQuery: string
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  listUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 正常にユーザー一覧を返却します */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListUsersResponse']
        }
      }
      /** @description 認証に失敗しました */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ユーザーID(UUID) */
        id: components['parameters']['UserId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 正常にユーザー情報を返却します */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      /** @description リクエスト内容が不正、または UUID が不正です */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description 指定されたユーザーが存在しません */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  updateUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ユーザーID(UUID) */
        id: components['parameters']['UserId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest']
      }
    }
    responses: {
      /** @description 更新が成功しました（レスポンスボディなし） */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description リクエスト内容が不正です */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description 指定されたユーザーが存在しません */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  signup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest']
      }
    }
    responses: {
      /** @description 登録が成功しました */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SignupResponse']
        }
      }
      /** @description リクエスト内容が不正です */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  signin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SigninRequest']
      }
    }
    responses: {
      /** @description サインインに成功しました */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SigninResponse']
        }
      }
      /** @description リクエスト内容が不正です */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description 認証に失敗しました（メールまたはパスワードが不正） */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  listWorkSpaces: {
    parameters: {
      query?: {
        /** @description ページ番号 */
        page?: components['parameters']['Page']
        /** @description 1ページあたりの件数 */
        per_page?: components['parameters']['PerPage']
        /** @description 検索クエリ（名前などでフィルタリング） */
        search_query?: components['parameters']['SearchQuery']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 正常にワークスペース一覧を返却します */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListWorkSpacesResponse']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  createWorkSpace: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWorkSpaceRequest']
      }
    }
    responses: {
      /** @description ワークスペースが正常に作成されました */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkSpaceWithMemberShips']
        }
      }
      /** @description バリデーションエラー */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getWorkSpace: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ワークスペースID(UUID) */
        id: components['parameters']['WorkSpaceId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 正常にワークスペース情報を返却します */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkSpaceWithMemberShips']
        }
      }
      /** @description ワークスペースが見つかりません */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  deleteWorkSpace: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ワークスペースID(UUID) */
        id: components['parameters']['WorkSpaceId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description ワークスペースが正常に削除されました */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description ワークスペースが見つかりません */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  updateWorkSpace: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ワークスペースID(UUID) */
        id: components['parameters']['WorkSpaceId']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateWorkSpaceRequest']
      }
    }
    responses: {
      /** @description ワークスペースが正常に更新されました（レスポンスボディなし） */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description バリデーションエラー */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description ワークスペースが見つかりません */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description サーバー内部エラー */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
}
