module Infrastructure
  module Repository
    module Rom
      module User
        class UserBaseRomRepository < ::ROM::Repository
          # relation accessor for this repository
          def users: () -> ::ROM::Relation
        end
      end
    end
  end
end
