name: "CI"
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  ci:
    env:
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18@sha256:69e8582b781cb44fa4557b98ed586fe68361e320d9b12f9707494335634f4f3d
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sample_db
        ports:
          - 15432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24
      - name: install libpq-dev
        run: sudo apt-get install -y libpq-dev
      - name: Install Infisical CLI
        run: |
          curl -1sLf https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh | sudo -E bash
          sudo apt-get -o DPkg::Lock::Timeout=60 install -y infisical

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.1"
          bundler-cache: true
          working-directory: apps/backend

      - name: Mark repo as safe for git
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: enable corepack
        run: corepack enable

      - name: yarn set v4
        run: yarn set version stable

      - name: yarn install
        run: yarn install

      - name: yarn check
        run: yarn check
        
