name: "CI"
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  ci:
    env:
      LOCAL_INFISICAL_CLIENT_ID: ${{ secrets.LOCAL_INFISICAL_CLIENT_ID }}
      LOCAL_INFISICAL_CLIENT_SECRET: ${{ secrets.LOCAL_INFISICAL_CLIENT_SECRET }}
      LOCAL_INFISICAL_PROJECT_ID: ${{ secrets.LOCAL_INFISICAL_PROJECT_ID }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18@sha256:22c89fe0d0f507606260237fd55e51f6137f58b2d5bcf6152242b96d9fe8f9a4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sample_db
        ports:
          - 15432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:8.8.0@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
        command: redis-server --requirepass password
        env:
          REDIS_PASSWORD: password
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli -a password ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
      - name: install libpq-dev
        run: sudo apt-get install -y libpq-dev
      - name: Install Infisical CLI
        run: |
          curl -1sLf https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh | sudo -E bash
          sudo apt-get -o DPkg::Lock::Timeout=60 install -y infisical

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.6"
          bundler-cache: true
          working-directory: apps/backend

      - name: Mark repo as safe for git
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: enable corepack
        run: corepack enable

      - name: Yarn install
        run: yarn install --immutable

      - name: Install Playwright browsers
        run: yarn workspace frontend exec playwright install --with-deps chromium

      - name: yarn check
        run: yarn check
        
